yazawaj.com m_string fix
WebBreacher/WhatsMyName pull request #851
Opened 2024-08-24 18:38 UTC by balestek

m_string has changed

2024-08-25 16:59 UTC, WebBreacher requested changes

2024-08-26 12:37 UTC, balestek commented on wmn-data.json
> -        "e_string" : "<title>Форум 3Dn Tech - Просмотр профиля:",
Hello,
The e_string in wmn-data.json is "<title>Форум **3Dn** Tech - Просмотр профиля:" while in the page source it's "Форум **3Dnews** Tech". As e_code and m_code are both 200, all checks fail.

2024-08-26 12:38 UTC, balestek commented on wmn-data.json
> +        "m_string": "message",
You are right

2024-08-26 12:39 UTC, WebBreacher commented on wmn-data.json
> -        "e_string" : "<title>Форум 3Dn Tech - Просмотр профиля:",
I see you are correct. Thank you.

2024-08-26 13:04 UTC, balestek commented on wmn-data.json
> -        "m_code" : 302,
You are right, I followed redirects, it's still 302 for m_code

2024-08-26 13:06 UTC, balestek commented on wmn-data.json
> +        "known": [
Do you want headers on a single line as well ?

2024-08-26 13:16 UTC, balestek commented
I've updated the code according to your comments. Don't pay attention to Blogger and DockerHub, I cancelled the changes about them in the last commit.

2024-08-26 13:16 UTC, WebBreacher commented on wmn-data.json
> +        "known": [
I don't think so due to wrapping. Sorry for the inconsistency but readability is important.

2024-08-26 13:25 UTC, balestek commented on wmn-data.json
> +        "known": [
Ok, headers have been changed to 1 line (Apex Legends and Avid Community)

2024-08-26 13:25 UTC, merged

2024-08-26 13:25 UTC, WebBreacher commented
Thanks for taking the time and effort to make these changes!!