New sites
WebBreacher/WhatsMyName pull request #915
Opened 2024-12-19 15:23 UTC by 3xp0rt

2024-12-20 01:11 UTC, WebBreacher requested changes
Please check comments and alter as needed. Thanks for all the work!!!

2024-12-20 01:11 UTC, WebBreacher commented on wmn-data.json
> +        "cat" : "hobby"
I believe this site should be `shopping`

2024-12-20 01:11 UTC, WebBreacher commented on wmn-data.json
> +        "known" : ["ke7_2024", "jpsol"],
Please check to see if `jpsol` works for you. I get an error. The other account works.

2024-12-20 18:33 UTC, 3xp0rt commented on wmn-data.json
> +        "m_string" : "class=\\'cc-error-page__msg\\'",
Yes, I missed it during debugging.

2024-12-26 16:37 UTC, WebBreacher approved these changes

2024-12-26 16:37 UTC, merged