New and fix
WebBreacher/WhatsMyName pull request #920
Opened 2024-12-29 16:54 UTC by 3xp0rt

2025-01-04 21:39 UTC, WebBreacher requested changes

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
>          "known" : ["Abdul01", "Abdullah"],
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +        "protection": ["cloudflare"]
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
>          "known" : ["desiaunty", "creatvmind"],
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
>         {
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
>          "cat" : "coding"
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +       },
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
>          "known" : ["johnny", "dev"],
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +       },
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +        "protection" : ["other"]
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
>          "cat" : "coding"
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> -        "uri_check" : "https://holopin.io/@{account}#",
I see this redirects to https://www.holopin.io as you found.

See above note for GETs vs POSTs. I think this one can be reworked to a working GET request by changing the `uri_check` to `https://www.holopin.io/@{account}`. Please confirm.

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
>          "m_code" : 404,
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
>         },
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
>          "known" : ["mohammed01", "mohammed03"],
Please double check this one. When I send I get the response shown at the 2 below. 
![image](https://github.com/user-attachments/assets/9a3c9408-f38c-41f9-a0e4-503d56c1b2c7)

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +       },
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +       },
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +       },
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +        "m_string" : "",
Suggest adding `<title>404 Not Found</title>` for `m_string`

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +       },
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
>          "known" : ["webbreacher", "SonOfSevenless"],
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
>         },
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +       },
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +        "protection" : ["other"]
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +       },
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +       },
No issues

2025-01-04 21:39 UTC, WebBreacher commented on wmn-data.json
> +        "name" : "ArchWiki",
This should be alphabetized up with the "A" entries please.

2025-01-10 10:44 UTC, 3xp0rt commented on wmn-data.json
>          "known" : ["mohammed01", "mohammed03"],
You're confusing it with leetcode.

2025-01-10 11:02 UTC, 3xp0rt commented on wmn-data.json
> -        "name" : "AnimePlanet",
You have developed a data schema that supports POST requests. Anyone wishing to use the WMN dataset must comply with the requirements of this data schema. Implementing a POST request in code is a straightforward task, typically taking about a minute. If someone overlooks this, the responsibility lies with them, not with the dataset. I believe that API requests should be prioritized regardless of the method, even POST method due to their fast response times and ease of detection.

2025-01-10 13:09 UTC, WebBreacher submitted a review, later dismissed

2025-01-10 13:09 UTC, WebBreacher commented on wmn-data.json
> -        "name" : "AnimePlanet",
I understand what you are saying. I also understand the state of the downstream tools and am preferring that, when possible, GETs be used over POSTs. In this case, I would like it reverted back to a GET.

2025-01-10 13:09 UTC, WebBreacher commented on wmn-data.json
> -        "uri_check" : "https://holopin.io/@{account}#",
Please revert to a GET.

2025-01-10 13:09 UTC, WebBreacher commented on wmn-data.json
>          "known" : ["mohammed01", "mohammed03"],
You are correct. Thank you.

2025-01-10 23:45 UTC, 3xp0rt commented on wmn-data.json
> -        "name" : "AnimePlanet",
This one uses CloudFlare, and the downstream tools can't even access it.

2025-01-29 23:38 UTC, merged